### ISSUE TITLE
About the results

### ISSUE THREAD

**Issue by AselSiriwardena** [Amr-Mustafa/zero-dce-net#1]
I have tested both authors' implementation and your implementation, but the test results are so unsatisfactory. They can't even be compared to the results in the paper. I want to know if that's a fault on my end or it's the way it is.

![image](https://user-images.githubusercontent.com/35985674/108816151-a7e4a800-75db-11eb-8cac-17c3fb659e88.png)

**Comment by Amr-Mustafa** [comment]
My implementation is not complete. It is effectively the same as the original author's implementation. However, when I tried his code, the results were good enough. There must be an issue on your side. Anyway, stick to the official repository.

**Comment by AselSiriwardena** [comment]
Thank you for the quick response. I have seen an issue made by you in their repository. That's why I asked to confirm if it's an issue on my side. Thank you again.
